/**
 * GET  /api/epl/sofia-brief  — latest Sofia/EA morning briefing (markdown) for
 *                              the Today panel widget.
 * POST /api/epl/sofia-brief  — store the latest briefing (x-api-key auth).
 *
 * The EA morning briefing is generated by a Claude run and posted to Slack
 * #sofia each morning. MC's bot is write-only on Slack, so instead of MC
 * pulling from Slack, the generator POSTs the markdown here after posting to
 * Slack — decoupled, no Slack read-scopes needed, works from any host.
 *
 * Stored at <dataDir>/sofia_brief.json = { markdown, postedAt, updatedAt }.
 * GET returns an honest empty state when nothing has been posted yet.
 */

import { NextRequest, NextResponse } from 'next/server'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { config } from '@/lib/config'

const BRIEF_PATH = path.join(config.dataDir, 'sofia_brief.json')

interface StoredBrief {
  markdown: string
  postedAt: string | null
  updatedAt: string
}

export async function GET() {
  if (!existsSync(BRIEF_PATH)) {
    return NextResponse.json({ source: 'empty', markdown: null, postedAt: null, note: 'No Sofia briefing posted yet.' })
  }
  try {
    const data = JSON.parse(readFileSync(BRIEF_PATH, 'utf8')) as StoredBrief
    return NextResponse.json({ source: 'stored', ...data })
  } catch (e) {
    return NextResponse.json({ source: 'error', markdown: null, postedAt: null, error: e instanceof Error ? e.message : 'unknown' }, { status: 500 })
  }
}

export async function POST(req: NextRequest) {
  const configured = (process.env.API_KEY || '').trim()
  const provided = (req.headers.get('x-api-key') || '').trim()
  if (!configured || provided !== configured) {
    return NextResponse.json({ error: 'unauthorized' }, { status: 401 })
  }
  let body: { markdown?: string; postedAt?: string }
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'invalid json body' }, { status: 400 })
  }
  if (!body.markdown || typeof body.markdown !== 'string') {
    return NextResponse.json({ error: 'markdown (string) is required' }, { status: 400 })
  }
  const stored: StoredBrief = {
    markdown: body.markdown,
    postedAt: body.postedAt ?? null,
    updatedAt: new Date().toISOString(),
  }
  try {
    writeFileSync(BRIEF_PATH, JSON.stringify(stored, null, 2), 'utf8')
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : 'write failed' }, { status: 500 })
  }
  return NextResponse.json({ ok: true, bytes: stored.markdown.length, postedAt: stored.postedAt })
}
